---
channel: stable
addons:
  paperless-ngx:
    repository: ashishs1/paperless-home-assistant-addon
    target: paperless-ngx
    image: ghcr.io/ashishs1/paperless-ngx/{arch}
  dashy:
    repository: BenoitAnastay/dashy-home-assistant-addon
    target: dashy
    image: ghcr.io/benoitanastay/dashy/{arch}
  heimdall:
    repository: BenoitAnastay/heimdall-home-assistant-addon
    target: heimdall
    image: ghcr.io/benoitanastay/heimdall/{arch}
  authelia:
    repository: BenoitAnastay/authelia-home-assistant-addon
    target: authelia
    image: ghcr.io/benoitanastay/authelia/{arch}
  tika-gotenberg:
     repository: BenoitAnastay/tika-gotenberg-home-assistant-addon
     target: tika-gotenberg
     image: ghcr.io/benoitanastay/tika-gotenberg/{arch}
